[build-system]
requires = [
    "flit_core ~=3.2",
    "bidict ~=0.19"
]
build-backend = "flit_core.buildapi"

[project]
name = "py-text-gen"
authors = [{name = "Belreau Cohen", email = "nuu.chah.nulth@disroot.org"}]
dynamic = ["version", "description"]

# [project.urls]
# Home = ""