name: CI Workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  linting-job:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Check Python version
        run: python --version
      - name: Install and use Pycodestyle
        run: |
          python -m pip install pycodestyle==2.8.0
          pycodestyle --statistics .